# Generated by Django 4.1.3 on 2022-11-18 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
